// Copyright 2026 Mower maintainers
// SPDX-License-Identifier: Apache-2.0
#include "mower_camera/camera_parameters.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <stdexcept>
namespace mower_camera { namespace { std::string uppercase(std::string value) { std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) {return std::toupper(c);}); return value; } }
void validate_camera_parameters(const CameraParameters & p) { if (p.width <= 0 || p.height <= 0) throw std::invalid_argument("width and height must be positive"); if (!std::isfinite(p.frame_rate) || p.frame_rate <= 0.0 || p.frame_rate > 240.0) throw std::invalid_argument("frame_rate must be finite and within (0, 240]"); if (p.frame_id.empty()) throw std::invalid_argument("frame_id must not be empty"); (void)image_encoding_for_pixel_format(p.pixel_format); }
std::string image_encoding_for_pixel_format(const std::string & f) { const auto v = uppercase(f); if (v == "YUYV" || v == "YUYV8") return "yuv422_yuy2"; if (v == "RGB888") return "rgb8"; if (v == "BGR888") return "bgr8"; if (v == "R8" || v == "Y8" || v == "MONO8") return "mono8"; throw std::invalid_argument("pixel_format must be YUYV, RGB888, BGR888, or R8/MONO8"); } }
namespace mower_camera { void validate_camera_controls(int exposure_time_us, double analogue_gain) { if (exposure_time_us < 0) throw std::invalid_argument("exposure_time_us must be non-negative"); if (!std::isfinite(analogue_gain) || analogue_gain < 0.0) throw std::invalid_argument("analogue_gain must be finite and non-negative"); }
void validate_calibrated_camera_info(const sensor_msgs::msg::CameraInfo & info, int expected_width, int expected_height) { if (info.width != static_cast<uint32_t>(expected_width) || info.height != static_cast<uint32_t>(expected_height)) throw std::invalid_argument("calibration image size does not match requested stream"); if (info.distortion_model.empty() || info.d.empty()) throw std::invalid_argument("calibration must contain a distortion model and coefficients"); if (info.k[0] <= 0.0 || info.k[4] <= 0.0 || info.p[0] <= 0.0 || info.p[5] <= 0.0) throw std::invalid_argument("calibration must contain positive focal lengths in K and P"); for (const auto value : info.k) if (!std::isfinite(value)) throw std::invalid_argument("calibration K contains a non-finite value"); for (const auto value : info.p) if (!std::isfinite(value)) throw std::invalid_argument("calibration P contains a non-finite value"); for (const auto value : info.d) if (!std::isfinite(value)) throw std::invalid_argument("calibration D contains a non-finite value"); }
void validate_image_buffer_layout(const ImageBufferLayout & l) { const auto encoding = image_encoding_for_pixel_format(l.pixel_format); const size_t bytes_per_pixel = encoding == "yuv422_yuy2" ? 2U : (encoding == "mono8" ? 1U : 3U); if (l.width == 0 || l.height == 0 || l.stride < l.width * bytes_per_pixel) throw std::invalid_argument("camera buffer has an invalid image stride"); const size_t required = static_cast<size_t>(l.stride) * l.height; if (l.bytes_used != required || l.mapped_length < required) throw std::invalid_argument("camera buffer size does not match image layout"); } }
